name: Generate Snake
on:
  schedule:
    - cron: "0 0 * * *"   # diário 00:00 UTC
  workflow_dispatch:

permissions:
  contents: write   # precisa para criar/atualizar a branch 'output'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Widson64x
          outputs: |
            dist/snake.svg

      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
