name: Profile Summary Cards
on:
  schedule:
    - cron: "0 4 * * *"   # diário 04:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: Widson64x
          BRANCH_NAME: main
          EXCLUDE: issues
